[project]
name = "gittools"
version = "1.3"
description = "Miscellaneous utilities to get more out of git"
authors = [{ name = "Alice Purcell", email = "alicederyn@gmail.com" }]
requires-python = ">= 3.12"
dynamic = ["dependencies"]

[project.scripts]
git-continuous-fetch = "gittools.continuous_fetch:main"
git-graph-branch = "gittools.git_graph_branch:main"
git-mirror = "gittools.git_mirror:main"
git-pr = "gittools.git_pr:main"
git-rebase-branch = "gittools.git_rebase_branch:main"
git-split-pick = "gittools.git_split_pick:main"
git-watch-status = "gittools.watch_status:main"

[tool.ruff]
target-version = "py312"

[tool.ruff.lint]
select = ["B", "E", "F", "I", "PYI", "RUF", "SIM", "UP", "W"]
isort.split-on-trailing-comma = false

[tool.setuptools.dynamic]
dependencies = { file = ["requirements.txt"] }

[build-system]
requires = ["setuptools >= 75"]
build-backend = "setuptools.build_meta"
